let age = 16; // мой возраст
let year = 2004; // год рождения
let bithday = 21 // число рождения
let numberOfSublings = 1; // количество братьев
let numberOfSisters = 1;//  сестер
let family = 6;// человек в семье
let fare = 150;// стоимость проезда
let thisYear = 2020; // год
let dollarRate = "72.55rub" // курс доллара
let euroRate = "82.59rub" //   евро
let bitcoinRate = "2450 361.06rub" // биткоина
let minus = thisYear - Year;//
let minus2 = thisYear - age;//
let plus = numberOfSublings + numberOfSisters; //
let zvez = euroRate / 1000;
let dl = dollarRate  * 2.5;
let bit = bitcoinRate / 10000
let far = fare / dollarRate;
let fam = family - numberOfSisters;
let nan = 0 / age;
let mins = 35 - age;